# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alan/CLionProjects/gameServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alan/CLionProjects/gameServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alan/CLionProjects/gameServer/CMakeFiles /home/alan/CLionProjects/gameServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alan/CLionProjects/gameServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gameServer

# Build rule for target.
gameServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gameServer
.PHONY : gameServer

# fast build rule for target.
gameServer/fast:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/build
.PHONY : gameServer/fast

GameServer.o: GameServer.cpp.o

.PHONY : GameServer.o

# target to build an object file
GameServer.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/GameServer.cpp.o
.PHONY : GameServer.cpp.o

GameServer.i: GameServer.cpp.i

.PHONY : GameServer.i

# target to preprocess a source file
GameServer.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/GameServer.cpp.i
.PHONY : GameServer.cpp.i

GameServer.s: GameServer.cpp.s

.PHONY : GameServer.s

# target to generate assembly for a file
GameServer.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/GameServer.cpp.s
.PHONY : GameServer.cpp.s

TCPServer.o: TCPServer.cpp.o

.PHONY : TCPServer.o

# target to build an object file
TCPServer.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/TCPServer.cpp.o
.PHONY : TCPServer.cpp.o

TCPServer.i: TCPServer.cpp.i

.PHONY : TCPServer.i

# target to preprocess a source file
TCPServer.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/TCPServer.cpp.i
.PHONY : TCPServer.cpp.i

TCPServer.s: TCPServer.cpp.s

.PHONY : TCPServer.s

# target to generate assembly for a file
TCPServer.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/TCPServer.cpp.s
.PHONY : TCPServer.cpp.s

UDPServer.o: UDPServer.cpp.o

.PHONY : UDPServer.o

# target to build an object file
UDPServer.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/UDPServer.cpp.o
.PHONY : UDPServer.cpp.o

UDPServer.i: UDPServer.cpp.i

.PHONY : UDPServer.i

# target to preprocess a source file
UDPServer.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/UDPServer.cpp.i
.PHONY : UDPServer.cpp.i

UDPServer.s: UDPServer.cpp.s

.PHONY : UDPServer.s

# target to generate assembly for a file
UDPServer.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/UDPServer.cpp.s
.PHONY : UDPServer.cpp.s

logsys/gs_log.o: logsys/gs_log.cpp.o

.PHONY : logsys/gs_log.o

# target to build an object file
logsys/gs_log.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/logsys/gs_log.cpp.o
.PHONY : logsys/gs_log.cpp.o

logsys/gs_log.i: logsys/gs_log.cpp.i

.PHONY : logsys/gs_log.i

# target to preprocess a source file
logsys/gs_log.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/logsys/gs_log.cpp.i
.PHONY : logsys/gs_log.cpp.i

logsys/gs_log.s: logsys/gs_log.cpp.s

.PHONY : logsys/gs_log.s

# target to generate assembly for a file
logsys/gs_log.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/logsys/gs_log.cpp.s
.PHONY : logsys/gs_log.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/main.cpp.s
.PHONY : main.cpp.s

modules/Game.o: modules/Game.cpp.o

.PHONY : modules/Game.o

# target to build an object file
modules/Game.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Game.cpp.o
.PHONY : modules/Game.cpp.o

modules/Game.i: modules/Game.cpp.i

.PHONY : modules/Game.i

# target to preprocess a source file
modules/Game.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Game.cpp.i
.PHONY : modules/Game.cpp.i

modules/Game.s: modules/Game.cpp.s

.PHONY : modules/Game.s

# target to generate assembly for a file
modules/Game.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Game.cpp.s
.PHONY : modules/Game.cpp.s

modules/Map.o: modules/Map.cpp.o

.PHONY : modules/Map.o

# target to build an object file
modules/Map.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Map.cpp.o
.PHONY : modules/Map.cpp.o

modules/Map.i: modules/Map.cpp.i

.PHONY : modules/Map.i

# target to preprocess a source file
modules/Map.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Map.cpp.i
.PHONY : modules/Map.cpp.i

modules/Map.s: modules/Map.cpp.s

.PHONY : modules/Map.s

# target to generate assembly for a file
modules/Map.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Map.cpp.s
.PHONY : modules/Map.cpp.s

modules/Player.o: modules/Player.cpp.o

.PHONY : modules/Player.o

# target to build an object file
modules/Player.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Player.cpp.o
.PHONY : modules/Player.cpp.o

modules/Player.i: modules/Player.cpp.i

.PHONY : modules/Player.i

# target to preprocess a source file
modules/Player.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Player.cpp.i
.PHONY : modules/Player.cpp.i

modules/Player.s: modules/Player.cpp.s

.PHONY : modules/Player.s

# target to generate assembly for a file
modules/Player.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Player.cpp.s
.PHONY : modules/Player.cpp.s

modules/Session.o: modules/Session.cpp.o

.PHONY : modules/Session.o

# target to build an object file
modules/Session.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Session.cpp.o
.PHONY : modules/Session.cpp.o

modules/Session.i: modules/Session.cpp.i

.PHONY : modules/Session.i

# target to preprocess a source file
modules/Session.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Session.cpp.i
.PHONY : modules/Session.cpp.i

modules/Session.s: modules/Session.cpp.s

.PHONY : modules/Session.s

# target to generate assembly for a file
modules/Session.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/modules/Session.cpp.s
.PHONY : modules/Session.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/gameServer.dir/build.make CMakeFiles/gameServer.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gameServer"
	@echo "... GameServer.o"
	@echo "... GameServer.i"
	@echo "... GameServer.s"
	@echo "... TCPServer.o"
	@echo "... TCPServer.i"
	@echo "... TCPServer.s"
	@echo "... UDPServer.o"
	@echo "... UDPServer.i"
	@echo "... UDPServer.s"
	@echo "... logsys/gs_log.o"
	@echo "... logsys/gs_log.i"
	@echo "... logsys/gs_log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... modules/Game.o"
	@echo "... modules/Game.i"
	@echo "... modules/Game.s"
	@echo "... modules/Map.o"
	@echo "... modules/Map.i"
	@echo "... modules/Map.s"
	@echo "... modules/Player.o"
	@echo "... modules/Player.i"
	@echo "... modules/Player.s"
	@echo "... modules/Session.o"
	@echo "... modules/Session.i"
	@echo "... modules/Session.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

